apiVersion: v1
kind: Service
metadata:
  name: canary-svc
  namespace: canary
  labels:
    {{- include "canary.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "canary.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: stable-svc
  namespace: canary
  labels:
    {{- include "canary.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "canary.selectorLabels" . | nindent 4 }}
